[package]
name = "rust-advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"

[[bin]]
name = "01"
path = "src/01/01.rs"

[[bin]]
name = "02"
path = "src/02/02.rs"

[[bin]]
name = "03"
path = "src/03/03.rs"

[[bin]]
name = "04"
path = "src/04/04.rs"
